/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_lab131;

import Estructuras.*;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.table.DefaultTableModel;
import objetos.*;

/**
 *
 * @author DAYNOR
 */
public class Ejercicio1 extends javax.swing.JFrame {
    private CCircularPro prodGral = new CCircularPro();
    private CSimpleMercadoMin mercadosMin;
    private PilaMercadoMay mercadosMay;
    
    public CCircularPro getProdGral() {
        return prodGral;
    }

    public void setProdGral(CCircularPro prodGral) {
        this.prodGral = prodGral;
    }

    public CSimpleMercadoMin getMercadosMin() {
        return mercadosMin;
    }

    public void setMercadosMin(CSimpleMercadoMin mercadosMin) {
        this.mercadosMin = mercadosMin;
    }

    public PilaMercadoMay getMercadosMay() {
        return mercadosMay;
    }

    public void setMercadosMay(PilaMercadoMay mercadosMay) {
        this.mercadosMay = mercadosMay;
    }
    /**
     * Creates new form Ejercicio1
     */
    public Ejercicio1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreProd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(177, 208, 224));
        jPanel2.setForeground(new java.awt.Color(0, 0, 51));

        jButton2.setBackground(new java.awt.Color(177, 208, 224));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hogar .png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Mercados que tienen el producto buscado");

        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Intro Nombre Producto");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Mercados en donde se encuentra el producto ingresado:");

        tablaMers.setBackground(new java.awt.Color(204, 204, 204));
        tablaMers.setFont(new java.awt.Font("Sitka Small", 0, 13)); // NOI18N
        tablaMers.setForeground(new java.awt.Color(0, 0, 51));
        tablaMers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Hora Apertura", "Hora Cierre", "Macrodistrito", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMers);
        if (tablaMers.getColumnModel().getColumnCount() > 0) {
            tablaMers.getColumnModel().getColumn(0).setResizable(false);
            tablaMers.getColumnModel().getColumn(1).setResizable(false);
            tablaMers.getColumnModel().getColumn(2).setResizable(false);
            tablaMers.getColumnModel().getColumn(3).setResizable(false);
            tablaMers.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(nombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton1)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            limpiar();
            listaMerca1(obtIdOProd(this.nombreProd.getText(),new CCircularPro()));
            listaMerca2(obtIdOProd(this.nombreProd.getText(),new CCircularPro()));
        } catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
     private String obtIdOProd(String nombre, CCircularPro aux){
        int nro = prodGral.nroelem();
        String id = "";
        for (int i = 0; i < 10; i++) {
            Producto px = prodGral.eliminar();
            prodGral.adicionar(px);
            if(px.getNombre().equalsIgnoreCase(nombre))
                id = px.getIdProd();
        }
        return id;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaInicio ini = new VentanaInicio();
        ini.setProdsGral(prodGral);
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    // EJERCICIO 1---------------------------- 
    public void listaMerca1(String idProd) throws IOException{
        ObjectInputStream Registro = null;
        try{
            Registro = new ObjectInputStream(new FileInputStream("datos1.dat"));
            while(true){
                mercadosMin = new CSimpleMercadoMin();
                mercadosMin = (CSimpleMercadoMin)Registro.readObject();
                //------------------------------------------------
                CSimpleMercadoMin aux = new CSimpleMercadoMin();
            while(!mercadosMin.esvacia()){
                MercadoMinorista mxx = mercadosMin.eliminar();
                aux.adicionar(mxx);
                if(tienePro(mxx.getPuestos(),idProd))
                    adicionarTabla(mxx.getNombre(),mxx.getHoraApertura(), mxx.getHoraCierre(),mxx.getMacrodistrito(),mxx.getDireccion());
            }
            mercadosMin.vaciar(aux);
        //-----------------------------------------------------
            }
            
        } catch(Exception e){
            System.out.println(e);
        }
        finally{
            Registro.close();
        }
 
    }
    public void listaMerca2(String idProd) throws IOException{
        ObjectInputStream Registro = null;
        try{
            Registro = new ObjectInputStream(new FileInputStream("datos2.dat"));
            while(true){
                mercadosMay = new PilaMercadoMay();
                mercadosMay = (PilaMercadoMay)Registro.readObject();
                
                PilaMercadoMay aux = new PilaMercadoMay();
            while(!mercadosMay.esvacia()){
                MercadoMayorista mxx = mercadosMay.eliminar();
                aux.adicionar( mxx);
                if(sectorTiene(mxx.getSectores(),mxx.getCamiones(),idProd))
                    adicionarTabla(mxx.getNombre(),mxx.getHoraApertura(), mxx.getHoraCierre(),mxx.getMacrodistrito(),mxx.getDireccion());
        }
        mercadosMay.vaciar(aux);
        
            }
            
        } catch(Exception e){
            System.out.println(e);
        }
        finally{
            Registro.close();
        }
    }
    public boolean sectorTiene(PilaSe sec, LDobleCa cam, String idpro){
        if(tieneProdSe(sec,idpro)||tienePuest(cam.getP(),idpro))
            return true;
        return false;
    }
    public boolean tieneProdSe(PilaSe sec, String id){
        PilaSe aux = new PilaSe();
        boolean sw = false;
        while(!sec.esvacia()){
            Sector sx = sec.eliminar();
            if(tienePro(sx.getPuestos(),id))
                sw = true;
            aux.adicionar(sx);
        }
        return sw;
    }
      public boolean tienePro(LSimpleCPu cp, String idProd){
         NodoPu r = cp.getP();
         while(r.getSig()!=cp.getP()){
             if(tieneProdu(r.getPuest().getProductos().getP(), idProd))
                 return true;
             r = r.getSig();
         }
         if(tieneProdu(r.getPuest().getProductos().getP(), idProd)){
            return true;}
         return false;
     }
     public boolean tieneProdu(NodoPr r, String id){
         if(r!=null){
             if(r.getIdProducto().equalsIgnoreCase(id))
                 return true;
             return tieneProdu(r.getSig(), id);
         }else
             return false;
     }
    public boolean tienePuest(NodoCa r,String id){
        if(r!=null){
            if(tieneProdu(r.getCamion().getProductos().getP(),id))
                return true;
            return tienePuest(r.getSig(), id);
        } else
            return false;
    }
 
   
   
     private void adicionarTabla(String nombre, String horaA, String horaC, String macro, String direc) {
        DefaultTableModel datos = (DefaultTableModel)this.tablaMers.getModel();
        Object[] fila = new Object[5];
        fila[0] = nombre;
        fila[1] = horaA;
        fila[2] = horaC;
        fila[3] = macro;
        fila[4] = direc;
        datos.addRow(fila);
    }
    public void limpiar() {
        DefaultTableModel datos = (DefaultTableModel)tablaMers.getModel();
        int n = this.tablaMers.getRowCount()-1;
        for(int i = n; i >=0 ; i--){
            datos.removeRow(this.tablaMers.getRowCount()-1);
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreProd;
    private javax.swing.JTable tablaMers;
    // End of variables declaration//GEN-END:variables
}
