/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_lab131;

import Estructuras.*;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.table.DefaultTableModel;
import objetos.*;

/**
 *
 * @author DAYNOR
 */
public class Ejercicio4 extends javax.swing.JFrame {
        private CCircularPro prodGral = new CCircularPro();
    private CSimpleMercadoMin mercadosMin;
    private PilaMercadoMay mercadosMay;
    
    public CCircularPro getProdGral() {
        return prodGral;
    }

    public void setProdGral(CCircularPro prodGral) {
        this.prodGral = prodGral;
    }

    public CSimpleMercadoMin getMercadosMin() {
        return mercadosMin;
    }

    public void setMercadosMin(CSimpleMercadoMin mercadosMin) {
        this.mercadosMin = mercadosMin;
    }

    public PilaMercadoMay getMercadosMay() {
        return mercadosMay;
    }

    public void setMercadosMay(PilaMercadoMay mercadosMay) {
        this.mercadosMay = mercadosMay;
    }
    /**
     * Creates new form Ejercicio4
     */
    public Ejercicio4() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomMer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSec = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(177, 208, 224));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hogar .png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Small", 0, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Sectores del mercado mayorista donde se encuentran productos con menor precio");

        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Mercado mayorista");

        nomMer.setFont(new java.awt.Font("Sitka Small", 0, 13)); // NOI18N

        jButton1.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mostrar.png"))); // NOI18N
        jButton1.setText("Listar Sectores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaSec.setBackground(new java.awt.Color(204, 204, 204));
        tablaSec.setFont(new java.awt.Font("Sitka Small", 0, 13)); // NOI18N
        tablaSec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Superficie", "Nro puestos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaSec);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(nomMer, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomMer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            limpiar();
            
            mostrarMercadosMay();
        } catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          VentanaInicio ini = new VentanaInicio();
        ini.setProdsGral(prodGral);
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
        public void mostrarMercadosMay() throws IOException{
        ObjectInputStream Registro = null;
        try{
            
            Registro = new ObjectInputStream(new FileInputStream("datos2.dat"));
            while(true){
                mercadosMay = new PilaMercadoMay();
                mercadosMay = (PilaMercadoMay)Registro.readObject();
                
                double meno=0;
                PilaMercadoMay aux = new PilaMercadoMay();
            while(!mercadosMay.esvacia()){
                MercadoMayorista mxx = mercadosMay.eliminar();
                aux.adicionar( mxx);
                if(mxx.getNombre().equalsIgnoreCase(this.nomMer.getText())){
                    meno = elMenorDeSectores(mxx.getSectores());
                    //System.out.println("menor: meno:  "+meno);
                    mostrar(meno,mxx.getSectores());
                }
        }
        mercadosMay.vaciar(aux);
            
            }
            
        } catch(Exception e){
            System.out.println(e);
        }
        finally{
            Registro.close();
        }
    }
    public void mostrar(double men, PilaSe se){
        PilaSe aux = new PilaSe();
        while(!se.esvacia()){
            Sector sx = se.eliminar();
            aux.adicionar(sx);
            if(elMenorPuestos(sx.getPuestos())==men)
                adicionarTabla(sx.getNombre(), sx.getSuperficie(), contarPuestos(sx.getPuestos()));
        }
        se.vaciar(aux);
    }
     
        
        public double elMenorDeSectores(PilaSe se){
        PilaSe aux = new PilaSe();
        double men = 9999;
        while(!se.esvacia()){
            Sector s = se.eliminar();
            aux.adicionar(s);
            double meee = elMenorPuestos(s.getPuestos());
            if(meee<men)
                men = meee;
        }
        se.vaciar(aux);
        return men;
    }
    public double elMenorPuestos(LSimpleCPu lp){
        NodoPu r = lp.getP();
        double men = 99999;
        while(r.getSig()!=lp.getP()){
            double elme = elMenorPre(r.getPuest().getProductos().getP());
            if(elme<men)
                men = elme;
            r = r.getSig();
        }
        double elme = elMenorPre(r.getPuest().getProductos().getP());
            if(elme<men)
                men = elme;
        return men;
    }
    public double elMenorPre(NodoPr r){
        if(r!=null){
            double men = elMenorPre(r.getSig());
            if(r.getPrecio()<men)
                men = r.getPrecio();
            return men;
        } else
            return 99999;
    }
    public int contarPuestos(LSimpleCPu pu){
           NodoPu r = pu.getP();
           int c = 0;
           while(r.getSig()!=pu.getP()){
               c++;
               r = r.getSig();
           }
           c++;
           return c;
       }
        private void adicionarTabla(String nombre, int superf, int nroPu) {
        DefaultTableModel datos = (DefaultTableModel)this.tablaSec.getModel();
        Object[] fila = new Object[3];
        fila[0] = nombre;
        fila[1] = superf;
        fila[2] = nroPu;
        datos.addRow(fila);
    }
    public void limpiar() {
        DefaultTableModel datos = (DefaultTableModel)tablaSec.getModel();
        int n = this.tablaSec.getRowCount()-1;
        for(int i = n; i >=0 ; i--){
            datos.removeRow(this.tablaSec.getRowCount()-1);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomMer;
    private javax.swing.JTable tablaSec;
    // End of variables declaration//GEN-END:variables
}
