/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_lab131;
import Estructuras.*;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.*;
/**
 *
 * @author DAYNOR
 */
public class VentanaMerMay1 extends javax.swing.JFrame {
    private PilaMercadoMay mercadosMay = new PilaMercadoMay();
    private CCircularPro prodGral = new CCircularPro();

    public CCircularPro getProdGral() {
        return prodGral;
    }

    public void setProdGral(CCircularPro prodGral) {
        this.prodGral = prodGral;
    }
    public void setMercadosMay(PilaMercadoMay mercadosMay) {
        this.mercadosMay = mercadosMay;
    }

    public PilaMercadoMay getMercadosMay() {
        return mercadosMay;
    }
    /**
     * Creates new form VentanaMerMay1
     */
    public VentanaMerMay1(String mer) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //llenarDatos();
    }
    public VentanaMerMay1() {
        initComponents();
        this.setLocationRelativeTo(null);
        //llenarDatos();
    }
    /*public void llenarDatos(){
        LSimplePr prod0001 = new LSimplePr();
        prod0001.adifinal("pro1", 11, "1 libra");
        prod0001.adifinal("pro3", 5, "1 libra");
        
        LSimplePr prod0002 = new LSimplePr();
        prod0001.adifinal("pro4", 8, "1 libra");
        prod0001.adifinal("pro5", 19, "1 kilo");
        
        LDobleCa cam1 = new LDobleCa();
        cam1.adifinal(new CamionProductos("ca1","achocalla",prod0001));
        cam1.adifinal(new CamionProductos("ca2","sorata",prod0002));
        
        LSimpleCPu pue001 =  new LSimpleCPu();
        pue001.adiultimo(new Puesto("pu001",prod0001));
        pue001.adiultimo(new Puesto("pu001",prod0002));
        
        LSimpleCPu pue002 =  new LSimpleCPu();
        pue002.adiultimo(new Puesto("pu001",prod0002));
        pue002.adiultimo(new Puesto("pu001",prod0001));
        
        PilaSe sec001 = new PilaSe();
        sec001.adicionar(new Sector("frutas",12,pue001));
        sec001.adicionar(new Sector("verduras",14,pue002));
        mercadosMay.adicionar(new MercadoMayorista("Uruguay","8:00","21:00","Max Paredes","c. max paredes", 123,cam1,sec001));
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMerMay = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(177, 208, 224));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 0, 23)); // NOI18N
        jLabel1.setText("MERCADOS MAYORISTAS LA PAZ");

        listar.setBackground(new java.awt.Color(204, 204, 204));
        listar.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portapapeles.png"))); // NOI18N
        listar.setText("Listar");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar (2).png"))); // NOI18N
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaMerMay.setBackground(new java.awt.Color(204, 204, 204));
        tablaMerMay.setFont(new java.awt.Font("Sitka Small", 0, 13)); // NOI18N
        tablaMerMay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "HoraApertura", "HoraCierre", "Macrodistrito", "Direccion", "Superficie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMerMay);
        if (tablaMerMay.getColumnModel().getColumnCount() > 0) {
            tablaMerMay.getColumnModel().getColumn(0).setResizable(false);
            tablaMerMay.getColumnModel().getColumn(1).setResizable(false);
            tablaMerMay.getColumnModel().getColumn(2).setResizable(false);
            tablaMerMay.getColumnModel().getColumn(3).setResizable(false);
            tablaMerMay.getColumnModel().getColumn(4).setResizable(false);
            tablaMerMay.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista-de-verificacion.png"))); // NOI18N
        jButton3.setText("Ver Camiones y Sectores");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regreso.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(listar)
                                .addComponent(jButton2)))
                        .addGap(70, 70, 70)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(listar)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3)
                        .addGap(59, 59, 59)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarDatos() throws IOException {
   
        ObjectInputStream Registro = null;
        try{
            Registro = new ObjectInputStream(new FileInputStream("datos2.dat"));
            while(true){
                mercadosMay = new PilaMercadoMay();
                mercadosMay = (PilaMercadoMay)Registro.readObject();
                PilaMercadoMay aux = new PilaMercadoMay();
            while(!mercadosMay.esvacia()){
                MercadoMayorista mxx = mercadosMay.eliminar();
                aux.adicionar( mxx);
                adicionarTabla(mxx.getNombre(),mxx.getHoraApertura(), mxx.getHoraCierre(),mxx.getMacrodistrito(),mxx.getDireccion(),mxx.getSuperficie());
        }
        mercadosMay.vaciar(aux);
            }
            
        } catch(Exception e){
            System.out.println(e);
        }
        finally{
            Registro.close();
        }
      
    }
    private void adicionarTabla(String nombre, String horaA, String horaC, String macro, String direc, int suo) {
        DefaultTableModel datos = (DefaultTableModel)this.tablaMerMay.getModel();
        Object[] fila = new Object[8];
        fila[0] = nombre;
        fila[1] = horaA;
        fila[2] = horaC;
        fila[3] = macro;
        fila[4] = direc;
        fila[5] = suo;
        datos.addRow(fila);
    }
    private void limpiar() {
        DefaultTableModel datos = (DefaultTableModel)tablaMerMay.getModel();
        int n = this.tablaMerMay.getRowCount()-1;
        for(int i = n; i >=0 ; i--){
            datos.removeRow(this.tablaMerMay.getRowCount()-1);
        }
    }
    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        try{
        limpiar();
        cargarDatos();
        } catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_listarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginAdmin logi = new LoginAdmin("mayorista");
        logi.setProdGral(prodGral);
        logi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int x = this.tablaMerMay.getSelectedRow();
        String nomMer = (String) this.tablaMerMay.getValueAt(x, 0);
        VentanaSectorCamion secCam = new VentanaSectorCamion(nomMer);
        secCam.setProdGral(prodGral);
        secCam.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        VentanaInicio ini = new VentanaInicio();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMerMay1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMerMay1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMerMay1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMerMay1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMerMay1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listar;
    private javax.swing.JTable tablaMerMay;
    // End of variables declaration//GEN-END:variables
}
