/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_lab131;
import Estructuras.*;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.*;
/**
 *
 * @author DAYNOR
 */
public class VentanaMerMen extends javax.swing.JFrame {
    private CSimpleMercadoMin mercadosMin;
    private CCircularPro prodGral;

    public CCircularPro getProdGral() {
        return prodGral;
    }

    public void setProdGral(CCircularPro prodGral) {
        this.prodGral = prodGral;
    }
    public void setMercadosMin(CSimpleMercadoMin mercadosMin) {
        this.mercadosMin = mercadosMin;
    }

    public CSimpleMercadoMin getMercadosMin() {
        return mercadosMin;
    }
    /**
     * Creates new form VentanaMerMen
     */
    public VentanaMerMen(String mer) {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public VentanaMerMen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMerMen = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(177, 208, 224));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("MERCADOS MINORISTAS DE LA PAZ");

        tablaMerMen.setBackground(new java.awt.Color(204, 204, 204));
        tablaMerMen.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        tablaMerMen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NombreMercado", "Hora Apertura", "Hora Cierre", "Macrodistrito", "Direccion", "Superficie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMerMen);
        if (tablaMerMen.getColumnModel().getColumnCount() > 0) {
            tablaMerMen.getColumnModel().getColumn(0).setResizable(false);
            tablaMerMen.getColumnModel().getColumn(1).setResizable(false);
            tablaMerMen.getColumnModel().getColumn(2).setResizable(false);
            tablaMerMen.getColumnModel().getColumn(3).setResizable(false);
            tablaMerMen.getColumnModel().getColumn(4).setResizable(false);
            tablaMerMen.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portapapeles.png"))); // NOI18N
        jButton1.setText("Listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionar.png"))); // NOI18N
        jButton2.setText("Seleccionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regreso.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel2)
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(21, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1)
                        .addGap(59, 59, 59)
                        .addComponent(jButton2)
                        .addGap(59, 59, 59)
                        .addComponent(jButton3)
                        .addGap(45, 45, 45)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        limpiar();
        cargarDatosList();
        } catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void cargarDatosList() throws IOException{
      
        ObjectInputStream Registro = null;
        try{
            Registro = new ObjectInputStream(new FileInputStream("datos1.dat"));
            while(true){
                mercadosMin = new CSimpleMercadoMin();
                mercadosMin = (CSimpleMercadoMin)Registro.readObject();
                // codigo para mostrar
                CSimpleMercadoMin aux = new CSimpleMercadoMin();
            while(!mercadosMin.esvacia()){
                MercadoMinorista mxx = mercadosMin.eliminar();
                aux.adicionar(mxx);
                adicionarTabla(mxx.getNombre(),mxx.getHoraApertura(), mxx.getHoraCierre(),mxx.getMacrodistrito(),mxx.getDireccion(),mxx.getSuperficie());
        }
        mercadosMin.vaciar(aux);
        // HAASTAA AKIII
            }
            
        } catch(Exception e){
            System.out.println(e);
        }
        finally{
            Registro.close();
        }
 
    }
     private void adicionarTabla(String nombre, String horaA, String horaC, String macro, String direc, int superf) {
        DefaultTableModel datos = (DefaultTableModel)this.tablaMerMen.getModel();
        Object[] fila = new Object[6];
        fila[0] = nombre;
        fila[1] = horaA;
        fila[2] = horaC;
        fila[3] = macro;
        fila[4] = direc;
        fila[5] = superf;
        datos.addRow(fila);
    }
    public void limpiar() {
        DefaultTableModel datos = (DefaultTableModel)tablaMerMen.getModel();
        int n = this.tablaMerMen.getRowCount()-1;
        for(int i = n; i >=0 ; i--){
            datos.removeRow(this.tablaMerMen.getRowCount()-1);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = this.tablaMerMen.getSelectedRow();
        String nomMer = (String) this.tablaMerMen.getValueAt(x, 0);
        VentanaPuestosProMen men = new VentanaPuestosProMen("minorista",nomMer);
        men.setMercadosMino(mercadosMin);
        men.setProdGral(prodGral);
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoginAdmin logi = new LoginAdmin("minorista");
        logi.setProdGral(prodGral);
        logi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       VentanaInicio ini = new VentanaInicio();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMerMen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMerMen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMerMen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMerMen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMerMen().setVisible(true);
            }
        });
    }

   /* private void llenarDatos() {
        LSimpleCPu pu001 = new LSimpleCPu();
        
        LSimplePr prod021 = new LSimplePr();
        prod021.adifinal("pro2", 12, "1 libra");
        prod021.adifinal("pro3", 4, "1 libra");
        prod021.adifinal("pro5", 7, "1 libra");
   
        LSimplePr prod022 = new LSimplePr();
        prod022.adifinal("pro4", 11, "1 libra");
        prod022.adifinal("pro5", 12, "1 libra");

        LSimplePr prod023 = new LSimplePr();
        prod023.adifinal("pro1", 10, "1 kilo");
        prod023.adifinal("pro6", 4, "1 libra");
        prod023.adifinal("pro6", 1, "1 libra");

        LSimplePr prod024 = new LSimplePr();
        prod024.adifinal("pro2", 21, "1 kilo");
        prod024.adifinal("pro4", 7, "1 libra");

        LSimplePr prod025 = new LSimplePr();
        prod025.adifinal("pro5", 4, "1 libra");
        prod025.adifinal("pro3", 4, "1 libra");
        prod025.adifinal("pro11", 21, "1 arroba");

        pu001.adiultimo(new Puesto("p021",prod021));
        pu001.adiultimo(new Puesto("p022",prod022));
        pu001.adiultimo(new Puesto("p023",prod023));
        pu001.adiultimo(new Puesto("p024",prod024));
        pu001.adiultimo(new Puesto("p025",prod025));
        mercadosMin.adicionar(new MercadoMinorista("bolivar","08:00","21:00","periferica","av juan jose torres",400,pu001));
  
        LSimpleCPu pu002 = new LSimpleCPu();
        
        LSimplePr prod031 = new LSimplePr();
        prod031.adifinal("pro1", 12, "1 libra");
        prod031.adifinal("pro5", 6, "1 libra");
        prod031.adifinal("pro7", 5, "1 libra");
   
        LSimplePr prod032 = new LSimplePr();
        prod032.adifinal("pro6", 9, "1 libra");
        prod032.adifinal("pro2", 7, "1 libra");

        LSimplePr prod033 = new LSimplePr();
        prod033.adifinal("pro7", 10, "1 kilo");
        prod033.adifinal("pro3", 14, "1 libra");
        prod033.adifinal("pro6", 11, "1 libra");

        LSimplePr prod034 = new LSimplePr();
        prod034.adifinal("pro5", 2, "1 kilo");
        prod034.adifinal("pro2", 4, "1 libra");

        LSimplePr prod035 = new LSimplePr();
        prod035.adifinal("pro6", 6, "1 libra");
        prod035.adifinal("pro4", 5, "1 libra");
        prod035.adifinal("pro1", 2, "1 libra");

        pu002.adiultimo(new Puesto("p031",prod031));
        pu002.adiultimo(new Puesto("p032",prod032));
        pu002.adiultimo(new Puesto("p033",prod033));
        pu002.adiultimo(new Puesto("p034",prod034));
        pu002.adiultimo(new Puesto("p035",prod035));
        mercadosMin.adicionar(new MercadoMinorista("velas","08:00","21:00","centro","av litoral",500,pu002));

    
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMerMen;
    // End of variables declaration//GEN-END:variables
}
